kernel: generic: fix perf build breakage on 4.19
Drop 211-host_tools_portability.patch which is breaking perf build on
4.19 kernels by removing the include directory from the host's CFLAGS
leading to the following build breakage:

 pmu-events/jevents.c:48:10: fatal error: linux/list.h: No such file or directory
  #include <linux/list.h>
           ^~~~~~~~~~~~~~

Signed-off-by: Petr Štetiar <ynezz@true.cz>